name: Push to Niks3 cache
description: A set of steps to push Nix derivations to the Niks3 cache.
inputs:
  niks3_version:
    description: The version of Niks3 to use.
    required: false
    default: "v1.4.0"
  oidc_audience:
    description: The OIDC audience to use for requesting Niks3 tokens. If not
      provided, no token will be requested.
    required: false
    default: ""
  niks3_server_url:
    description: The URL of the Niks3 server to push to.
    required: true
  paths_to_push:
    description: A newline-separated list of /nix/store paths to push to Niks3.
    required: true
  verify_s3_integrity:
    description: Verify that objects in database actually exist in S3 before skipping upload
    required: false
    default: "false"

runs:
  using: composite
  steps:
    - name: Download niks3 binary
      shell: bash
      env:
        VERSION: ${{ inputs.niks3_version }}
      run: |
        OS="${{ runner.os }}"
        if [ "$OS" = "macOS" ]; then
          OS="Darwin"
        fi

        ARCH="${{ runner.arch }}"
        if [ "$ARCH" = "X64" ]; then
          ARCH="x86_64"
        elif [ "$ARCH" = "ARM64" ]; then
          ARCH="arm64"
        fi

        URL="https://github.com/Mic92/niks3/releases/download/${VERSION}/niks3_${OS}_${ARCH}.tar.gz"

        echo "Downloading from $URL"
        wget "$URL" -O niks3.tar.gz
        tar -xzf niks3.tar.gz

    - name: Fetch OIDC token
      id: oidc
      if: ${{ inputs.oidc_audience != '' }}
      shell: bash
      run: |
        token=$(curl -s \
          -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
          "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${{ inputs.oidc_audience }}" \
          | jq -r '.value')

        echo "::add-mask::${token}"
        echo "token=${token}" >> "$GITHUB_OUTPUT"

    - name: Push derivations to cache
      shell: bash
      env:
        NIKS3_AUTH_TOKEN: ${{ steps.oidc.outputs.token }}
        PATHS_TO_PUSH: ${{ inputs.paths_to_push }}
        NIKS3_SERVER_URL: ${{ inputs.niks3_server_url }}
      run: |
        args=(--server-url "$NIKS3_SERVER_URL")

        if [ "${{ inputs.verify_s3_integrity }}" = "true" ]; then
          args+=(--verify-s3-integrity)
        fi

        if [ -n "$NIKS3_AUTH_TOKEN" ]; then
          args+=(--auth-token "$NIKS3_AUTH_TOKEN")
        fi

        readarray -t paths <<< "$PATHS_TO_PUSH"

        ./niks3 push "${args[@]}" "${paths[@]}"
